# Based on https://blog.dev-web.io/2019/02/10/utiliser-symfony-dans-docker/
# https://stackoverflow.com/questions/54479941/how-to-init-mysql-database-in-docker-compose
version: '3'
services:

    php730:
        build: php73
        container_name: ${CONTAINER_NAME_PREFIX}_php730
        ports:
            - "9073:80"
        volumes:
            - ./apache2/sites-enabled:/etc/apache2/sites-enabled
            - ${PROJECT_DIR}:/var/www

    # https://nodejs.org/fr/docs/guides/nodejs-docker-webapp/
    nodejs10:
        build: nodejs10
        container_name: ${CONTAINER_NAME_PREFIX}_nodejs10
        ports:
            - "49160:8080"

    mysql57:
        image: mysql:5.7
        container_name: ${CONTAINER_NAME_PREFIX}_mysql57
        ports:
            - "3307:3306"
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_USER: 'root'
        volumes:
            - ./mysql-initdb:/docker-entrypoint-initdb.d
            - ./mysql57/my.cnf:/etc/mysql/conf.d/custom.cnf
            - ${MYSQL_DATA_DIR}:/var/lib/mysql
            - ${MYSQL_LOG_DIR}:/var/log/mysql

    swagger:
        image: swaggerapi/swagger-ui
        container_name: ${CONTAINER_NAME_PREFIX}_swagger
        ports:
            - "9000:8080"
        volumes:
            - ./../project/web/_tests/scripts/swagger.json:/docs/swagger.json
        environment:
            - SWAGGER_JSON="/docs/swagger.json"

    # https://maxhopei.github.io/2019/06/26/Integrating-Blackfire-io-with-Docker-Compose/
    blackfire:
        image: blackfire/blackfire
        container_name: ${CONTAINER_NAME_PREFIX}_blackfire
        environment:
            BLACKFIRE_LOG_LEVEL: 4
            BLACKFIRE_SERVER_ID: ${BLACKFIRE_SERVER_ID}
            BLACKFIRE_SERVER_TOKEN: ${BLACKFIRE_SERVER_TOKEN}
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}
            BLACKFIRE_LOG_FILE: /tmp/blackfire.log
        volumes:
            - ${BLACKFIRE_LOGS_DIR}:/tmp

    maildev:
        image: maildev/maildev
        container_name: ${CONTAINER_NAME_PREFIX}_maildev
        ports:
            - "8002:80"

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${CONTAINER_NAME_PREFIX}_phpmyadmin
        ports:
            - "8080:80"
        depends_on:
            - mysql57
        environment:
            PMA_HOST: ${CONTAINER_NAME_PREFIX}_mysql57
